# Generated by Django 4.0.3 on 2022-03-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('certification', models.CharField(blank=True, max_length=100)),
                ('role_important', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=100)),
                ('role_level', models.CharField(blank=True, max_length=100)),
                ('role_time', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=100)),
                ('sponsorship', models.CharField(blank=True, max_length=100)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('specific_industry', models.CharField(blank=True, max_length=100)),
                ('veteran', models.CharField(blank=True, max_length=100)),
                ('disability', models.CharField(blank=True, max_length=100)),
                ('expected_salary', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='Website')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='Zipe Code')),
                ('survey', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='talent.survey')),
            ],
        ),
    ]
