# Generated by Django 4.0.3 on 2022-03-19 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talent', '0002_alter_survey_certification_alter_survey_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
    ]
